### PR TITLE
update users can only edit notes if they created it

### PR DESCRIPTION
**Pull request by roseeichelmann**
## Associated issues

Closes https://github.com/cityofaustin/atd-data-tech/issues/9874

This PR updates the notes section so that users can only edit a row in the notes section if they created it.

## Testing
**URL to test:** 

This can be tested locally or as a Netlify preview (https://deploy-preview-1089--atd-vze-staging.netlify.app/#/dashboard)

**Steps to test:**

1. Click on Crashes tab.
2. Go to crash 1036 (https://deploy-preview-1089--atd-vze-staging.netlify.app/#/crashes/1036).
3. You should not be able to edit or delete any notes unless they were created by you (Updated By column).
4. Try adding a new note and make sure you can edit then save it, edit then cancel, delete, etc.
5. You can check out some other crashes as well, some crashID's with dummy notes data in them include: 17164366, 18851626, 17727381.

---
#### Ship list
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
I can only edit my notes. Looks good! 🤘
Screen Shot 2022-08-01 at 6 47 37 AM

**Review by patrickm02L — CHANGES_REQUESTED** [review]
This is a bit of scope creep, but since it's an easy fix let's remove the line about the titles so that there's consistency between the notes and recommendations components? 
Notes remove line

**Review by patrickm02L — APPROVED** [review]
So nice without that line! This is good to go. 🤘

Screen Shot 2022-08-01 at 4 50 59 PM

**Review by mateoclarke — APPROVED** [review]
🚢💨✨

**Pull request merged**
