### PR TITLE
Process Dependabot PRs for VZV

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

This PR is part of the work to close https://github.com/cityofaustin/atd-data-tech/issues/14729.

This updates libraries specific to the VZV interactive map.

## Note

Of the 3 VZ Dependabot PRs, this one came with no surprises and is just a plain ol' library update.

## Testing

https://deploy-preview-1335--atd-vzv-staging.netlify.app/

* Check out the map and turn everything on and off. Everything map related is fair game.

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
clicked around the map and all the functionality is as usual!

**Review by mddilley — APPROVED** [review]
I also couldn't find any regression with the map. Drawing a boundary works just like it did before! 🚀 🙏 🚢

**Comment by mddilley** [comment]
@patrickm02L This is completely unrelated to this PR, but I noticed that, when drawing a boundary, the info box that appears with the injury and fatality counts overlaps the geocoder search box. I didn't expect that to happen. It is the same in production.
Screenshot 2024-01-08 at 5 40 15 PM

**Comment by patrickm02L** [comment]
> @patrickm02L This is completely unrelated to the changes in this PR, but I noticed that, when drawing a boundary, the info box that appears with the injury and fatality counts overlaps the geocoder search box. I didn't expect that to happen. It is the same in production. Screenshot 2024-01-08 at 5 40 15 PM

Thanks @mddilley. Good catch, here's the Issue to address it [#15182](https://github.com/cityofaustin/atd-data-tech/issues/15182)

**Review by patrickm02L — APPROVED** [review]
Looks good 🥏

**Pull request merged**
