### PR TITLE
v1.44.1

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/16608
- https://github.com/cityofaustin/atd-data-tech/issues/16558

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Comment by johnclary** [comment]
I will open a separate PR for prod once this is approved 🙏

**Review by mddilley — APPROVED** [review]
Tested the VZV update locally - looks great! 🚢 🚀🚢

**Review by chiaberry — APPROVED** [review]
visited the link by pasting the browser, 👍🏼

**Comment by johnclary** [comment]
thank you!!!!

**Pull request merged**
