### PR TITLE
Adds new micromobility and e-scooter types

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/11324

this pr adds the 'micromobility device' type and 'e-scooter' body style to the units table to supersede the micromobility flag on the crash table

## Testing
**URL to test:** 
[staging](https://visionzero-staging.austinmobility.io/editor/#/)

**Steps to test:**
- go to a crash
- in the units table, edit the type to 'micromobility device' and save
- edit the body style to 'e-scooter' and save
- refresh the page, the data should persist

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
Very Nice! 🚢 

https://github.com/cityofaustin/atd-vz-data/assets/5566727/b7d14748-693a-4d90-b263-469d886ede56

**Review by mddilley — APPROVED** [review]
Tested on staging, and this works great! 🚢 🚀🚢

**Comment by tillyw** [comment]
ran these commands on production without any issues! new records are in so i'm closing this out

**Comment by johnclary** [comment]
in the issue thread @chiaberry mentioned updating the [data dictionary](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ve3sp7qA5cPXha0B4/data-dictionary) as part of this work. i'd really like to see some brief descriptions of the relevant tables and their values documented. i'm a bit confused how this relates to the [overloaded lookup values](https://austininnovation.slack.com/archives/CM9MK950S/p1683139687194449?thread_ts=1683060101.205649&cid=CM9MK950S) so i 'm hoping the documentation would help me there.

**Comment by tillyw** [comment]
> in the issue thread @chiaberry mentioned updating the [data dictionary](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ve3sp7qA5cPXha0B4/data-dictionary) as part of this work. i'd really like to see some brief descriptions of the relevant tables and their values documented. i'm a bit confused how this relates to the [overloaded lookup values](https://austininnovation.slack.com/archives/CM9MK950S/p1683139687194449?thread_ts=1683060101.205649&cid=CM9MK950S) so i 'm hoping the documentation would help me there.

@johnclary thanks for pointing that out! i will update the data dictionary. to answer your question briefly - i talked with @frankhereford and we decided to add these entries to the existing lookup tables because this is a short term solution that will be addressed in the ldm, which will supersede the overloaded lookup table. we also figured it's really unlikely txdot will make changes to the lookup tables before then so this seemed like the best approach!

**Pull request merged**
