### PR TITLE
v2.0.2

### PR DESCRIPTION
**Pull request by johnclary**
* Handle smaller cr3 pdf page size (#1529) @johnclary
* Move victim name to the right of people table (#1532) @roseeichelmann
* WSOD when viewing a deleted crash (#1531) @roseeichelmann
* Drop all legacy tables, views, functions and metadata (#1522) @johnclary
* Ignore more table data in `vision-zero` helper script (#1528) @johnclary
* Fixes bug in `crashes_list_view.is_manual_geocode` (#1530) @johnclary

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Comment by johnclary** [comment]
i won't merge this until i run the legacy object migrations by hand first.

**Review by roseeichelmann — APPROVED** [review]
:rocket:

**Review by chiaberry — APPROVED** [review]
🚢 a nice chunk of really good updates here

**Comment by johnclary** [comment]
i’m having a `drop` party in VZ prod now...

**Pull request merged**
