### PR TITLE
change gender to sex in demographics section and info popup

### PR DESCRIPTION
**Pull request by roseeichelmann**
## Associated issues
Closes cityofaustin/atd-data-tech/issues/10910

## Testing
**URL to test:** 
https://deploy-preview-1128--atd-vzv-staging.netlify.app/

**Steps to test:**
Make sure that all instances of "Gender" have been changed to "Sex" (in the "By Demographics" chart and info pop up)

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by tillyw — APPROVED** [review]
looks good to me! thanks for updating this. my only question is whether the package-lock file can be uncommitted?

**Review by patrickm02L — APPROVED** [review]
Good to go! 🤘

**Comment by roseeichelmann** [comment]
@tillyw oops didnt even realize that commit, ill try to uncommit it!

**Review by frankhereford — CHANGES_REQUESTED** [review]
@roseeichelmann thank you for updating this language on the site. I think this is a very important distinction to make, and I appreciate you handling this.

~Your PR includes changes to the `package-lock.json` file, which I believe may be the result of running `npm install` or similar. I don't think we want this file to be merged into main, at least not at this time.~

~Do you agree? If so and if it's helpful to you, I would be happy to push a commit to your branch which reverts this change, if you'd like. Please let me know if I can help in any way. ~

Should have been a better reader and a slower typer - I see that you all are way ahead of me. Thank you for considering this! Approval incoming.

Thanks!

**Review by frankhereford — APPROVED** [review]

**Review by chiaberry — APPROVED** [review]

**Review by mddilley — APPROVED** [review]
Thanks for addressing this in the public facing viewer! 🙏  While we are on the topic of npm stuff, maybe we could create a backlog issue to add a `.nvmrc` to the VZ apps like [John added to the Moped Editor](https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/.nvmrc).

**Comment by tillyw** [comment]
@roseeichelmann thanks for clarifying that! i know there are cases where we want to include `package-lock.json` in our commits and i always wonder when those are. this is helpful to know!

**Comment by patrickm02L** [comment]
> Thanks for addressing this in the public facing viewer! 🙏 While we are on the topic of npm stuff, maybe we could create a backlog issue to add a `.nvmrc` to the VZ apps like [John added to the Moped Editor](https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/.nvmrc).

Created #11023 to address package-lock.

**Pull request merged**
