### PR TITLE
Workaround for CR3 PDF retrieval, with user supplied session tokens / cookies

### PR DESCRIPTION
**Pull request by mateoclarke**
~THIS PR IS NOT INTENDED FOR MERGING AT THIS TIME~

🧀 🍷 This PR is well-aged and is ready to make its debut.

_This ~temporary~ change to our `process_cris_cr3.py` script can only be performed from local dev environments. It will not work as an automated process in Airflow with the rest of our ETLs. I'm only opening this PR to make it easier to reference @frankhereford's solution so that other devs may checkout this branch and perform the retrieval task locally as needed._

_Documentation for how to manually retrieve a cookie from the browser with an active CRIS session [here](https://github.com/cityofaustin/atd-data-tech/issues/7815#issuecomment-981931328)._

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/7801
https://github.com/cityofaustin/atd-data-tech/issues/7815
https://github.com/cityofaustin/atd-data-tech/issues/7900

## Testing
~Test locally following ETL docs:~
~https://github.com/cityofaustin/atd-vz-data/tree/master/atd-etl#getting-started~

I think we get testing for free on this one - it's been used in production for over a year.

### CODE REVIEW

**Comment by patrickm02L** [comment]
Downloading CR3s Skillshare [Video]( https://web.microsoftstream.com/video/22214f55-bbb1-4764-b73f-4a0367b4150d)

**Review by chiaberry — APPROVED** [review]
thoroughly tested!

Once this is merged, we need to update the gitbook docs to say "use master" instead of this branch. 

Thank you!!!!

**Review by mddilley — APPROVED** [review]
🍪 🚀

**Comment by roseeichelmann** [comment]
🚢🚢🚢

**Review by roseeichelmann — APPROVED** [review]
🚢🚢🚢

**Review by patrickm02L — APPROVED** [review]
🍪 🍪 🍪

**Pull request merged**
