### PR TITLE
Update comprehensive costs for 2024 ( to account for inflation )

### PR DESCRIPTION
**Pull request by roseeichelmann**
## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/14980

## Testing
**URL to test:** 
Local

**Steps to test:**
1. Checkout this branch locally
2. Replicate the VZD to get a fresh copy of prod data and start up your local database.
3. Run `hasura migrate apply --up 1`
4. Ensure the values were updated correctly
5. Run `hasura migrate apply --down 1` make sure this runs and updates correctly
6. You can also run the VZE and see the new note in the VZE landing page talking about the comp costs.

---
#### Ship list
- [x] Check migrations for any conflicts with latest migrations in master branch
- [x] Confirm Hasura role permissions for necessary access
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Comment by roseeichelmann** [comment]
lol i did the thing again where i assigned everyone on accident instead of request reviewers :smile:

**Review by mddilley — APPROVED** [review]
Tested locally, and I see the updated notice in the VZE dahsboard. Up and down migrations update and restore the crash based costs too. Thanks!! 🚀

**Review by frankhereford — APPROVED** [review]
Thanks Rose! 🚢 🚢

**Review by patrickm02L — APPROVED** [review]
🚢

**Pull request merged**
