### PR TITLE
Adds scooter and motorcycle filters to crash table

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/7081

this pr updates the advanced filters on the crashes table to include motor vehicle, motorcycle and scooter rider, and remove motorized conveyance

## Testing
**URL to test:** 
https://deploy-preview-1226--atd-vze-staging.netlify.app/#/crashes

**Steps to test:**
- go to the crashes table and click advanced filters
- try each of the toggles and check one or two records to confirm the records match
- check the scooter rider filter. if there are no records initially, you may need to change an existing unit to type  'micromobility' style 'e-scooter'. change a scooter record to another mode and confirm it no longer appears in the scooter results.
- note the total number of records with no filters applied, then turn on all the filters. the number should be close to the total but missing a few records. we will write more queries to try to capture the missing records in a future pr.

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Comment by tillyw** [comment]
> Forgot to include this in the Issue - the title of this toggle section should be named "Unit Type"
> 
> Screen Shot 2023-05-18 at 7 32 00 AM

@patrickm02L updated!

**Review by mddilley — APPROVED** [review]
Awesome! I went through the test steps using the deploy preview, and every crash result that I checked had a unit with unit type that matched up with the toggles. Thanks for talking through the "Other" category in sprint planning too! 🙏 🚢

**Review by patrickm02L — APPROVED** [review]
## Approve
The functionality works like expected. Good to go! 🚀 

## Testing
- [X] go to the crashes table and click advanced filters
- [X] try each of the toggles and check one or two records to confirm the records match (:29-:49)
- [X] check the scooter rider filter. if there are no records initially, you may need to change an existing unit to type  'micromobility' style 'e-scooter'. change a scooter record to another mode and confirm it no longer appears in the scooter results. (:50-1:26)
- [X] note the total number of records with no filters applied, then turn on all the filters. the number should be close to the total but missing a few records.
   - got 4586 with all filters on, 4589 with no filters on 

## Notes
- Had to refresh to see the Crashes page after change pedestrian type to e-scooter.  (1:07)
- Happy to see the filters are an "or" relationship rather than an "and" so that each filter adds more types to the records display. (1:26-1:51)

https://github.com/cityofaustin/atd-vz-data/assets/5566727/6e63679b-174c-4557-879f-224611f4cf95

**Review by frankhereford — APPROVED** [review]
I tested the application and wrote up equivalent SQL queries based on my understanding of the meaning of the switches to confirm that the number of results coming back in the VZE matched. An example query for the pedestrians toggle is below for the date range set in the deploy preview VZE being reviewed.

```
select distinct crashes.crash_id
from atd_txdot_units units
join atd_txdot_crashes crashes on (units.crash_id = crashes.crash_id)
where units.unit_desc_id = 4
and crashes.crash_date >= '2022-05-22' and crashes.crash_date <= '2023-05-22'
and crashes.austin_full_purpose = 'Y'
and crashes.private_dr_fl <> 'Y'
```

I think this looks good. Tilly - thank you for your work coding this up and in particular decoding the correct way to write the graphql query snippets.

**Pull request merged**
