### PR TITLE
Exclude private drive crashes by default

### PR DESCRIPTION
**Pull request by roseeichelmann**
## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/11035

## Testing
**URL to test:** 
[Netlify link](https://deploy-preview-1198--atd-vze-staging.netlify.app/#/crashes)

**Steps to test:**
1. Go to the Crashes list page
2. On the advanced filters drop down, it should now say "Include Private Driveway Crashes" instead of "Exclude Private Driveway Crashes" on the Internal card.
3. By default, private driveway crashes are excluded. If you toggle the button, they will be included.

---
#### Ship list
- [ ] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
Good to go! 🚀 

https://user-images.githubusercontent.com/5566727/227005066-263a26a2-ef68-4752-8620-1ab3fb411fae.mp4

**Review by chiaberry — APPROVED** [review]

**Comment by roseeichelmann** [comment]
Oh also - i feel like this "Remove Austin Full Purpose" toggle is confusing bc it doesn't actually remove crashes within AFP, it just takes away the AFP requirement. So by default when the button is not toggled only crashes that are within AFP are shown and when its toggled all the crashes outside of AFP are also shown in addition to AFP crashes. Maybe this toggle could be improved too?

Like the name changed to "Include Outside of Austin Full Purpose"


image

**Comment by frankhereford** [comment]
@roseeichelmann wrote:

> Oh also - i feel like this "Remove Austin Full Purpose" toggle is confusing bc it doesn't actually remove crashes within AFP, it just takes away the AFP requirement. 

I totally agree. It feels backwards. I think your suggestion is 🎯💯. It's much more clear.

**Review by frankhereford — APPROVED** [review]
I spun this up locally, and it worked like a charm. Thanks Rose!!

**Pull request merged**
