### PR TITLE
Fix overlap in age groups on VZV

### PR DESCRIPTION
**Pull request by RR216**
This PR closes: https://github.com/cityofaustin/atd-data-tech/issues/12207
This is the deploy preview: https://deploy-preview-1268--atd-vzv-staging.netlify.app/
Details: change a typo that creates an overlap in the 55 year olds within 2 of the age groups on the Vision Zero Viewer: "46 to 55" and "55 to 64" on https://visionzero.austin.gov/viewer/.

### CODE REVIEW

**Review by mddilley — APPROVED** [review]
Looks great - thanks for fixing this typo! 🙏

**Review by johnclary — APPROVED** [review]
Nice! I see that this now matches [this other array](https://github.com/cityofaustin/atd-vz-data/blob/aac272e9b7abc55adc8ad90d23dd93329feb082e/atd-vzv/src/views/summary/PeopleByDemographics.js#L61) that powers the data groupings.

🚢 🚢 🚢 🚢 🚢

**Review by chiaberry — APPROVED** [review]

**Review by roseeichelmann — APPROVED** [review]
Thanks for fixing this Rachel!

**Review by patrickm02L — APPROVED** [review]
Good to go 🚢

**Pull request merged**
