### PR TITLE
update crash table ui to make vehicle type and body style editable

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/12161

this pr updates the crash table ui to make vehicle type and body style editable. once this [companion issue](https://github.com/cityofaustin/atd-data-tech/issues/11324) is complete, the vz team will be able to manually adjust units to be micromobility devices and we will then be able to do away with the micromobility device flag.

## Testing
**URL to test:** 
https://deploy-preview-1223--atd-vze-staging.netlify.app/#/crashes

**Steps to test:**
- go to a crash and select the units table
- edit the 'unit type' and save
- edit the 'body style' and save

you will be able to create some unusual combinations with these, but that is because the 'body style' lookup table is not associated with a particular 'unit type'

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
This is picture perfect. Code reads great and the UI works just like it should. This is 🚀🚀🚀

**Review by chiaberry — APPROVED** [review]
heh, unusual combinations is right.

**Review by mddilley — APPROVED** [review]
Works great on the deploy preview - can't wait to see what this work is going to unlock! 🚜 🚆 🛻 🚗 🛵

**Review by roseeichelmann — COMMENTED** [review]
this looks great, i can now edit the unit type and description! i noticed that when i click the edit button on the unit type or body style that the field in the input box changes automatically to whatever is at the top of the select list, but the other fields that i can edit dont do that. im not sure why these ones are behaving differently but it could be worth looking into so that users dont click save thinking they didnt actually pick something new and then are accidentally saving something they didnt mean to. lmk if that didnt make sense and i can explain better or demonstrate it lol!

**Review by mddilley — COMMENTED** [review]
Really great catch, @roseeichelmann! I think there is a missing key in the `unitDataMap` that helps the edit UI start with the existing value. 🔍 This came up recently in a review, but I can't find the PR.

**Comment by tillyw** [comment]
thanks for catching that, @roseeichelmann, and thanks for pointing me in the right direction, @mddilley! just fixed the issue and going to merge :)

**Comment by patrickm02L** [comment]
I sent this over to Xavier to see if the menus looked accurate. 

He said yes, that this is correct for what we currently have in the database, but we still wanted to but we still need to add the `MICROMOBILITY DEVICE` to the "TYPE" and `E-SCOOTER` to the "BODY STYLE" to capture the micromobility flag that we're getting rid of. 

Screen Shot 2023-05-04 at 11 01 18 AM

Screen Shot 2023-05-04 at 11 01 27 AM

**Review by patrickm02L — APPROVED** [review]
Good to go! 🚀

**Pull request merged**
