### PR TITLE
fixes wsod on vzv map page

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/9701

## Testing
**URL to test:** 
https://deploy-preview-1092--atd-vzv-staging.netlify.app/

**Steps to test:**
go to map, select council district overlay, click on a district!

Screen Shot 2022-08-10 at 5 22 20 PM

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
Good to go! 🤘

https://user-images.githubusercontent.com/5566727/184132967-1fc6d514-f8fb-4067-93fd-c08767f957d9.mp4

**Review by mateoclarke — CHANGES_REQUESTED** [review]
Though this does fix the reported bug and you are now able to click on a council district, it breaks the core functionality of being able to click a crash and see metadata next to the point on the map. This results in a new WSOD. I think this fix is too simplistic. Can you have a another look please?


https://user-images.githubusercontent.com/5697474/184172492-7f79969d-06af-44c0-9a6e-b9a1d1015a43.mov

**Comment by tillyw** [comment]
> Though this does fix the reported bug and you are now able to click on a council district, it breaks the core functionality of being able to click a crash and see metadata next to the point on the map. This results in a new WSOD. I think this fix is too simplistic. Can you have a another look please?
> 
>  bug.mov

i'm so sorry, thank you for pointing that out! investigating further.

**Comment by tillyw** [comment]
> Though this does fix the reported bug and you are now able to click on a council district, it breaks the core functionality of being able to click a crash and see metadata next to the point on the map. This results in a new WSOD. I think this fix is too simplistic. Can you have a another look please?
> 
>  bug.mov

fixed with a more programmatic approach that addresses both cases. thank you!

**Review by mateoclarke — APPROVED** [review]
🚢 💨 ✨

**Pull request merged**
