### PR TITLE
adds e-scooter rider to vzv map

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/12013

## Testing
**URL to test:** 
https://deploy-preview-1283--atd-vzv-staging.netlify.app/

**Steps to test:**
- go to the vzv map, you should see a new mode category for 'E-Scooter Rider'
- isolate that toggle and test it out under different categories and filters

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
## Review
This is so cool! 🛴 🤳 

Screen Shot 2023-08-31 at 3 34 22 PM

**Review by mddilley — APPROVED** [review]
Test steps work, and I like the new text key in the config! Thanks for getting this mode on the map too, and the numbers match up with what I'm seeing on the chart PR. 🚀

**Review by chiaberry — APPROVED** [review]
✨

**Comment by tillyw** [comment]
thanks, y'all! merging this one now :)

**Pull request merged**
