### PR TITLE
Add missing year of population data for VZV

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

none; WSOD on VZV since the new year. @patrickm02L, I think we should spin off an issue to make this not break annually. 

## Fun call-out

It's a small world: Karo's husband is listed as the data source for this data. https://github.com/cityofaustin/atd-vz-data/blob/add-population-estimate-for-2022-to-vzv/atd-vzv/src/constants/popEsts.js#L14

## Testing
https://deploy-preview-1148--atd-vzv-staging.netlify.app/

**Steps to test:**

Load the VZV - that's it!

---
#### Ship list
- [ ] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
Thanks for clearing this up. No more feeling blank! 🤘

**Review by chiaberry — APPROVED** [review]
thanks for catching this and fixing it quickly

**Comment by johnclary** [comment]
>  I think we should spin off an issue to make this not break annually.

+1

thanks @frankhereford!!

**Comment by patrickm02L** [comment]
Spin off Issue #11093

**Pull request merged**
