### PR TITLE
Update README with up-to-date CI details to trigger CI

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
n/a

This is a small update to the atd-events README to update it to say that GH Actions deploys the SQS + Lambda instead of saying that CircleCI does it. CircleCI only handles the deployment of the CR3 + user management API.

**Question:
**CircleCI uses the Docker Hub username/PW, and I know that we want to move to access tokens. Should this be done now or moved to be a less critical follow-up task?****

## Testing
**URL to test:** 
n/a

**Steps to test:**
Double check these configs to make sure this change will trigger the CircleCI and GH Action runs - it looks right to me but I could use some backup. 🙏 
https://github.com/cityofaustin/atd-vz-data/blob/master/.github/workflows/atd_sqs_build.yml
https://github.com/cityofaustin/atd-vz-data/blob/master/.github/workflows/atd_sqs_cleanup.yml
https://github.com/cityofaustin/atd-vz-data/blob/master/.circleci/config.yml

---
#### Ship list
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
🚀 Thank you Mike - can't wait to see this ship sail.

Also, the links you put in the comment - the first two, the workflows, by my read will be triggered by this change in `atd-events`.

**Comment by frankhereford** [comment]
I'm asking @patrickm02L to review this for PM approval too

**Review by patrickm02L — APPROVED** [review]
Small but mighty. 🤏

**Comment by johnclary** [comment]
looks good to me!

**Pull request merged**
