### PR TITLE
Fix CR3 downloads in staging

### PR DESCRIPTION
**Pull request by mateoclarke**
Works locally, but I need to merge to master to test in staging. Please feel free to review even though I'm merging w/o waiting for review.

### CODE REVIEW

**Comment by sergiogcx** [comment]
Cool-cool! 👍

**Comment by sergiogcx** [comment]
It works in staging now! :)

**Comment by mateoclarke** [comment]
lethal_weapon

**Comment by mateoclarke** [comment]
_Closes #424_

**Pull request merged**
