### PR TITLE
Update Fatality and Serious Injury counts for accuracy

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/7080

This PR updates the queries that power the dashboard to mirror the queries that populate the Socrata dataset that powers VZV. The years of life lost column for person and primary person records are now [generated columns](https://www.postgresql.org/docs/current/ddl-generated-columns.html) that are calculated from the `prsn_age` column in the same table.

The column follows these rules: 
a. if the injury severity is fatal, use 75 - person age to calculate years of life lost
b. if the injury severity is not fatal, use 0 for years of life lost
c. if 75 - person age is negative, use 0 for years of life lost

Thanks to @frankhereford for populating staging with production data - it made verifying the totals for this issue a breeze 🍃 

## Testing
**URL to test:** 
https://deploy-preview-1111--atd-vze-staging.netlify.app/

**Steps to test:**

**Widget counts**
1. Go to https://visionzero.austin.gov/viewer/
2. In a separate tab, go to https://deploy-preview-1111--atd-vze-staging.netlify.app/#/dashboard
3. Compare the counts in the widgets

**Locations years of life lost widget**
1. Go to https://deploy-preview-1111--atd-vze-staging.netlify.app/#/locations/05186FFEDB
2. In the **CR3 Crashes** card, enter a date range start of 09/29/2019 and end of 09/29/2022
3. You should see see one fatal crash (ID# 17662317) and the **Years of Life Lost widget** should show a total of 25
4. Go to https://deploy-preview-1111--atd-vze-staging.netlify.app/#/crashes/17662317 and see in the **Related Records People accordion**, and you will see that one person with the age of 50 passed away in this crash making the total years of life lost for this location 25 years for the entered date range

VZV totals as of September 15th, 2022
Screen Shot 2022-09-29 at 11 36 24 PM

VZE totals with this PR's code as of September 15th, 2022
Screen Shot 2022-09-29 at 11 37 33 PM

---
#### Ship list
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by patrickm02L — COMMENTED** [review]
This is phenomenal! Can flip the Fatalities and Years of Life Lost cards that way they're consistent with the order of the VZV widgets?

Screen Shot 2022-09-30 at 9 24 46 AM

**Review by frankhereford — APPROVED** [review]
Code reviewed and 👀 it on the deploy preview. This is just so welcome - to fix that glaring, out-in-front bug. Thank you!

**Comment by mddilley** [comment]
@patrickm02L I updated the widget order and also updated the serious injury widget to be yellow like VZV too (since there were two blue widgets side by side when reordered). Let me know if I need to walk back on that change. It is a very small change. 👍

**Comment by patrickm02L** [comment]
@mddilley good catch! Love that attention to detail. Keep the yellow.

**Review by patrickm02L — APPROVED** [review]
Everything looks stellar! 🤘

**Review by chiaberry — APPROVED** [review]

**Pull request merged**
