### PR TITLE
Update description of 'Other' modes in by travel mode modal

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/17102

## Testing
- Netlify

Check out the text in the By Travel Mode popup:
Screenshot 2024-05-02 at 12 09 13 PM

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by mddilley — APPROVED** [review]
Looks great in the deploy preview - thanks for updating! 🚢 🚀

**Review by chiaberry — APPROVED** [review]
👍🏼

**Review by roseeichelmann — APPROVED** [review]
:heavy_check_mark:

**Comment by johnclary** [comment]
thanks, y'all!

**Pull request merged**
