### PR TITLE
LDM Blueform crash location trigger

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues

**FYI: We are still feeling out how to test LDM work so open to any feedback! Going to discuss how this goes in the next LDM standup ~, and this should not get merged down into master branch~. It will be merged into a LDM collector branch ~that is soon to be unblocked~ that is now ready.**

https://github.com/cityofaustin/atd-data-tech/issues/12644

This PR adds the non-CR3 crash location association trigger to the LDM schema.

## Testing
**URL to test:** 
Local only

**Steps to test:**
1. To get a LDM data dump, use the command below. You will need to update the command with the path to your snapshots folder. The snipped part of the hostname and password for the LDM staging DB can be found in 1PW under the entry: `RDS Instance: LDM staging`. The command excludes the change log but will still take a moment.
```bash
PGHOST=ldm-staging.<snip>.us-east-1.rds.amazonaws.com \
PGDATABASE=atd_vz_data \
PGUSER=postgres \
PGPASSWORD=<snip> \
pg_dump \
--clean \
--create \
--if-exists \
--no-owner \
--no-privileges \
--exclude-table-data atd_txdot_change_log \
> /path/to/your/project/atd-vz-data/atd-vzd/snapshots/ldm_<today's date>.sql
```
3. If you can access the VZ read replica, then you should be able run this command. It is restricted to the same IPs as the replica through the security group called `visionzero-rds-read-replica`. We can add anyone who is looking to test this if needed.
4. Once you have the file in your snapshots folder, run `./vision-zero replicate-db -f <your filename>.sql` to restore from the LDM dump that you just made.
5. Connect to your local VZ database and you will know that it worked when you see the `cris` and `vision_zero` schemas.
6. Run the SQL in `atd-vzd/ldm_triggers/update_non_cr3_location/update_noncr3_location.sql`
7. Run the SQL in `atd-vzd/ldm_triggers/update_non_cr3_location/up.sql`
8. You can now run the test steps 1-4 in https://github.com/cityofaustin/atd-vz-data/pull/1269

---
#### Ship list
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by roseeichelmann — APPROVED** [review]
thanks for tackling this mike and for the comprehensive review steps! i was able to replicate from the ldm dump and see the trigger working in action, all the test steps worked as you outlined! :rocket:

**Comment by frankhereford** [comment]
@mddilley I think this can be rebased to the `ldm-collector` branch - do you think?

**Comment by mddilley** [comment]
@frankhereford yep - thanks for catching that! 🙏

**Review by frankhereford — APPROVED** [review]
Thank you Mike. This looks great, and it worked great. 

Here are the queries I've been using to look at these PRs, if they are helpful to anyone else. 

Thanks!

```
-- insert a blueform crash with coordinates that will associate to location_id 8337406736
INSERT INTO atd_apd_blueform(latitude, longitude, date, case_id)
VALUES (30.16841600, -97.78449000, '2023-08-14', '00000001');

-- insert a blueform crash with coordinates that will not associate to a location
INSERT INTO atd_apd_blueform(latitude, longitude, date, case_id)
VALUES (30.386136, -97.67309, '2023-08-14', '00000002');

-- insert a blueform crash without coordinates that will not associate to a location
INSERT INTO atd_apd_blueform(latitude, longitude, date, case_id)
VALUES (NULL, NULL, '2023-08-14', '00000003');

select case_id, latitude, longitude, location_id  from atd_apd_blueform crashes
where case_id in ('00000001', '00000002', '00000003', 140000003, 140000017)
order by case_id asc;

update atd_apd_blueform set latitude = 30.16841600, longitude = -97.78449000 where case_id = 140000003;

update atd_apd_blueform set latitude = 30.386136,   longitude = -97.67309    where case_id = 140000017;

select case_id, latitude, longitude, location_id  from atd_apd_blueform crashes
where case_id in ('00000001', '00000002', '00000003', 140000003, 140000017)
order by case_id asc;
```

**Comment by mddilley** [comment]
just pushed an update that covers a missed `location_id` case that Rose found [here](https://github.com/cityofaustin/atd-vz-data/pull/1286#discussion_r1318900687)

**Review by patrickm02L — APPROVED** [review]
Send it 🥏

**Comment by mddilley** [comment]
Noting here that this PR should be closed and **not merged** once we approve and merge https://github.com/cityofaustin/atd-vz-data/pull/1305 into the LDM collector branch. We get it for free with that work 🙌 😎

**Comment by mddilley** [comment]
Closing this now that the previously mentioned PR is merged into the collector branch. One trigger officially done! ✅ Thanks again, @frankhereford! 🙏

**Pull request closed without merging**
