### PR TITLE
Change data delay to two weeks ago

### PR DESCRIPTION
**Pull request by Charlie-Henry**
## Associated issues
[8129](https://github.com/cityofaustin/atd-data-tech/issues/8129)

## Testing
**URL to test:** 
Didn't test this, is there some way to perform this?
**Steps to test:**
Calling the function locally:

```
date.today()
->  datetime.date(2022, 4, 7)

get_date_limit()
-> '2022-03-24'
```

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Comment by mateoclarke** [comment]
Looks good from the code perspective but there should be a simple enough way to run this script locally, deploy to the Socrata test dataset and check to make sure the right data is being published. There's some README docs in the [atd-etl](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/README.md#getting-started) directory. Let's work on it together early next week

**Comment by Charlie-Henry** [comment]
Re-ran the `process_socrata_export.py` script in staging with the proposed changes today (4/12). The newest record showing in Socrata is dated March 28th, which is working as expected.
Screen Shot 2022-04-12 at 2 46 40 PM

I made a change to the `time.js` file which changes the date on the front end as well. It changed the date to March 29th on there. We state that it is "through" March 29th but we don't include data for the 29th. Not a big deal but we can just subtract one additional day on the front end side of things if this needs to be addressed. This also impacts the crash map where users can select up to March 29th.

Screen Shot 2022-04-12 at 2 52 50 PM

Screen Shot 2022-04-12 at 2 52 34 PM

@mateoclarke pointed out that we have a preview version of VZ viewer with a 1 month delay that'll be unnecessary after this is merged.

Appreciate pairing with @mateoclarke to help me test this!

**Review by mateoclarke — APPROVED** [review]
🚢 💨 ✨ 

rick-fortnite

**Review by patrickm02L — APPROVED** [review]
Rock and roll! 🚀

**Pull request merged**
