### PR TITLE
Updating VZ Dashboard

### PR DESCRIPTION
**Pull request by xavierapostol**
Updating dashboard to Dec 2023 Version

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by frankhereford — CHANGES_REQUESTED** [review]
First, thank you so much for making this PR! I think we may want to re-base this into main and go from there into production so that we don't accumulate commits in production that don't get into the main. I think we should touch on this topic real quick in our refinement meeting or possibly the next dev sync. Doing this will at least capture the state of the PDF in our release is going forward. Thanks again for doing a PR!

**Comment by mddilley** [comment]
+1 - that is a great idea @frankhereford about touching on this in refinement today! It would be great to get a process pinned down for all of us so we can get these into prod on the timeline needed.

**Comment by frankhereford** [comment]
Thanks Mike. I just had an idea that I wanted to put to paper for us to touch on in refinement. Maybe we wan to cleave this content out of the app and give VZ a S3 bucket and link to that from the app. Just bouncing around ideas. Might be easier for everyone.

**Comment by xavierapostol** [comment]
Just let me know what I need to do going forward. I want to make sure I don't create any havoc on y'all's end.

**Comment by patrickm02L** [comment]
## 1/17 
Discussed in Refinement, @frank to rebase from Production, and cherry pick a patch into Production. 

@patrickm02L will follow up with Xavier on alternative ways to host this dashboard PDF.

**Review by patrickm02L — APPROVED** [review]
Send it 🥏

**Review by frankhereford — APPROVED** [review]

**Review by chiaberry — APPROVED** [review]
🚢

**Review by mddilley — APPROVED** [review]
✅ 🚢

**Pull request merged**
