### PR TITLE
add micromobility to vzv chart

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/12005

## Testing
**URL to test:** 
[vzv](https://deploy-preview-1261--atd-vzv-staging.netlify.app/)
[vze](https://deploy-preview-1261--atd-vze-staging.netlify.app/)

**Steps to test:**
- Open VZV and confirm that the By Mode chart displays the new 'E-Scooter Rider' category with a new symbol and color from our existing color palette (we went with a phone icon because font awesome unfortunately doesn't have a scooter icon)
- References to this mode in the VZE fatalities and crashes tables should be consistent as well!

---
#### Ship list
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Review by mddilley — APPROVED** [review]
I tested this on the VZV and VZE deploy previews, and I see that the fatal outcomes for e-scooters match between the two. Awesome to see all your work culminate in seeing them represented on the dashboard. 🙏 🚢

**Review by chiaberry — APPROVED** [review]
👍🏼

**Review by patrickm02L — APPROVED** [review]
## Review

Very Nice! 📱 
Checked in the VZE when E-scooter toggle is on for 2023 and the count of 2 serious injuries was consistent with the VZV.

Screen Shot 2023-08-31 at 3 39 05 PM

**Comment by tillyw** [comment]
thanks, y'all!! :))

**Pull request merged**
