### PR TITLE
🤠 VZ Suite Dependabot Round Up (Python)

### PR DESCRIPTION
**Pull request by frankhereford**
# Dependabot Round Up for the Vision Zero Suite's Python λ functions and toolbox utilities

## Associated issues

_none_

This PR intends to address dependabot PRs which are open for this repo that relate to python libraries. It does not bring all libraries up to their latest version, rather, it targets the minimal update that resolves the requested changes in the dependabot PRs.

Because this PR ventures into the `atd-toolbox` utilities, the branch name may have been better chosen as `dependabot-round-up-python`, but the primary focus is on our λ functions.

## Contents

This PR contains merge commits from dependabot including:

* [Bump urllib3 from 1.25.8 to 1.26.5 in /atd-cr3-api](https://github.com/cityofaustin/atd-vz-data/commit/88a8b1974bda7bc234a20998379f95616d43ba7a)
* [Bump urllib3 in /atd-events/crash_update_noncr3_location](https://github.com/cityofaustin/atd-vz-data/commit/3888f5bb23065c17930cac91cb53b9d3fb9efd2e)
* [Bump urllib3 in /atd-events/crash_update_jurisdiction](https://github.com/cityofaustin/atd-vz-data/commit/aa56ad82657464e7da7328acc3e174d469d37c96)
* [Bump certifi from 2019.11.28 to 2022.12.7 in /atd-cr3-api](https://github.com/cityofaustin/atd-vz-data/commit/fb0230eec021d9968f9754e07aa04929fddd2a6f)
* [Bump certifi from 2019.11.28 to 2022.12.7 in /atd-cr3-api](https://github.com/cityofaustin/atd-vz-data/commit/fb0230eec021d9968f9754e07aa04929fddd2a6f)
* [Bump certifi in /atd-events/crash_update_location](https://github.com/cityofaustin/atd-vz-data/commit/e4f0722075468279d68dc1f24299b73bb9af24a4)
* [Bump certifi in /atd-toolbox/s3_restore_cr3_pdfs](https://github.com/cityofaustin/atd-vz-data/commit/002bad50d0f21db77f833498afef737fd0bf7ddb)
* [Bump certifi](https://github.com/cityofaustin/atd-vz-data/commit/29374c733e393376cba52fa6ac6eb7df17da5c77)
* [Bump certifi in /atd-events/crash_update_jurisdiction](https://github.com/cityofaustin/atd-vz-data/commit/068bfcee3e95ce7604f532640710252f3726aafa)
* [Bump certifi in /atd-events/crash_update_noncr3_location](https://github.com/cityofaustin/atd-vz-data/commit/7deb3667ea5a69d9761339698b112d9be6f6a5fa)
* [Bump future from 0.18.2 to 0.18.3 in /atd-cr3-api](https://github.com/cityofaustin/atd-vz-data/commit/c2f2d981f1d39003f8342c5bf422dd0846894545)

Due to the nature of `pip freeze` outputting libraries pinned to a specific release and that output being used as `requirements.txt` files, there were various times in this process that I had to loosen other library version to accommodate dependabot's requested upgrades. @johnclary, I believe, has observed that there better ways to specify library version requirements, and I'd be eager for his input on how we may better do this in the future.

## Process

Each application has been tested to see that `pip install -r requirements.txt` completes successfully in a fresh virtual environment. Further, λ functions have been executed to check to see if they compile and run in those same virtual environments. Toolbox applications have not been run in their environments, due to fear of unexpected side effects. That said, they are generally one-off scripts, and if needed, it will be a reasonable ask of the developer to use them with consideration of their contents. 

Presently, our CI for building staging λ functions is non-functional. Please see https://github.com/cityofaustin/atd-data-tech/issues/11371. 

## Testing

Testing may consist of creating a virtual environment and checking if libraries can be installed based on the specification in the various affected `requirements.txt` files. Additionally, when the staging λ deployment is restored, we should check the functionality of these scripts as they interact with the VZE.

However, these functions do deploy in the context of this PR deploy preview, so that is promising. I do not yet have enough experience with this CI to want to venture to say that this constitutes the testing we need, but I am optimistic.

---
#### Ship list
- [x] ~Code reviewed~
- [ ] Product manager approved

### CODE REVIEW

**Review by patrickm02L — APPROVED** [review]
Thanks for wrangling these up and updating. 🐍

**Review by mddilley — APPROVED** [review]
Tested installing all the requirements in virtual environments, and this looks solid! I didn't go too far down the rabbit hole of the failing GH action, but it does remind me of the [issue we had in Moped with dependabot-opened PRs](https://austininnovation.slack.com/archives/CNUEPKLB1/p1671738379276639) providing a branch name that the workflow helper script doesn't handle. 🚢 🚢 🚢 

Also, not sure if any discussion about version pinning affects this PR, so I'll take another look if needed. 👍

**Comment by frankhereford** [comment]
@mddilley wrote: 

> Also, not sure if any discussion about version pinning affects this PR, so I'll take another look if needed. 👍

I think it does apply. I think I misunderstood or didn't use correctly the correct `==\d.*` syntax to pin to the current version, and I will update these requirements.txt files to align with the suggestion that John gave on the other PR today. Thanks for pointing that out.

**Comment by frankhereford** [comment]
I have updated all instances where I was not using the equality operator with a wildcard version. Thanks again for finding that Mike.

**Review by roseeichelmann — APPROVED** [review]
thanks so much frank for addressing these dependabot PRs, its such a relief to see these getting merged! i tested installing all the requirements in a virtual env and they all successfully installed 🚢🚢🚢

**Pull request merged**
