### PR TITLE
Move previously ETL'd missing CR3 code into toolbox

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
This is not urgent at all. This is me wrapping up [this thread](https://austininnovation.slack.com/archives/CM9MK950S/p1700519268604239). TLDR: we decided to keep this code around after removing the DAG that ran it. I recently ran into it and mistook it for an active ETL so I thought it could go in the toolbox. See discussion and the removal of the DAG here -> https://github.com/cityofaustin/atd-airflow/pull/152/

## Testing
**URL to test:** 
n/a

**Steps to test:**
1. Do y'all agree that this could be moved to the toolbox?

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [x] Code reviewed
- [x] Product manager approved

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
I agree with moving it into the toolbox!

**Review by roseeichelmann — APPROVED** [review]
Yeah i agree thanks for cleaning this up!

**Review by patrickm02L — APPROVED** [review]
Thanks for cleaning this up 🧰

**Comment by mddilley** [comment]
@frankhereford This PR relates to [your investigation into the CR3 narrative and diagram regression](https://austininnovation.slack.com/archives/CM9MK950S/p1702038323069209). Do you think that I should still merge this?  iirc https://github.com/cityofaustin/atd-vz-data/pull/1328/ will reinstates the part of this ETL that fixes the regression.

**Comment by frankhereford** [comment]
Hey Mike! Thanks for putting this together!

I'm going to share my findings and proposed solution to the "fix cr3 narrative and diagram extraction" problem today in Dev Sync. The reason I mention that here is that I also have a PR waiting in the wings that I put together a few mornings ago when I was at the office early waiting for discovery day to start. My PR has a fair bit of overlap with this one, in that it removes all that same code out of the ETL directory, but does not move it into the toolbox. You can preview what I'm thinking here: https://github.com/cityofaustin/atd-vz-data/pull/1328. 

I gotta mention that my PR was put together because I felt like doing something with the time, and I totally know that I did it without scoping input or any input really from the group. Because of that, I'm a million times cool with closing my PR or changing it or anything really - it was an off-hours distraction for me.

Would it be cool if we sync'd up with the group today in dev sync before you merge this? If not, super no worries!! Thank you!!

**Comment by mddilley** [comment]
Frank and I messaged about this, and I'm holding off on merge until he gets a chance to take a look at this and after dev sync.

**Comment by mddilley** [comment]
@frankhereford Do you agree that I should close PR and not merge this now that https://github.com/cityofaustin/atd-vz-data/pull/1328 is merged? I don't think we need this in the toolbox anymore.

**Comment by frankhereford** [comment]
@mddilley Mike, I think closing this is a good move, because I don't see us needing the missing CR3 tooling. 

That said, I feel like I owe you an apology though for getting this work of yours tied up in the other PR that I merged today. I'm sorry for complicating your work, and I really appreciate what you did here to clean up these programs out of the ETL folder.

**Comment by mddilley** [comment]
All good, @frankhereford, happy to close this one! Thanks for getting to the bottom of this to get us back up and running. 🚀

**Pull request closed without merging**
