### PR TITLE
Remove the `_lkp` suffix from lookup tables

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/18569

## Testing

You know the deal! Run the CRIS import into your local stack and give the app a whirl:
1. Advanced search the crashes list
2. Export the crashes list
3. Edit a unit and people records using the drop-downs. Edit all the data table cards you can find.
4. Create a temp crash record
5. Search the locations list and export it
6. Open a location details and add a note
7. Check out the fatalities view

---
#### Ship list
- [ ] Check migrations for any conflicts with latest migrations in master branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

### CODE REVIEW

**Comment by johnclary** [comment]
👋 i'm requesting review on this even though the upstream branch isn't 100% complete 🙏

**Review by roseeichelmann — APPROVED** [review]
oof this must have been loads of `cntl + f` ing, thanks for cleaning this up!! this all looks good to me but on an unrelated note i feel like the crashes advanced search is so not straightforward in the way its working and filtering. i hope we get to refactor it a little bit in the future to make it more obvious. but this PR is good to go!!

**Review by mddilley — COMMENTED** [review]
This all looks perfect to me! Sooo many `_lkp`s removed! 🧹 I was able to do all the test steps except for one. When exporting from the locations page, I saw a graphql error that says `"field 'fatalities_count' not found in type: 'locations_list_view'"`. This seems unrelated to this diff, but I wanted to check before approving.

**Comment by johnclary** [comment]
ah, thanks, Mike! that bug comes from the upstream list view tweaks. i'll sort it out there :/

**Review by mddilley — APPROVED** [review]
🚢 🚢 🚢

**Pull request merged**
